### PR TITLE
Add test cases for promises

### PR DESCRIPTION
**Pull request by taion**
This illustrates #41. I have a fix incoming for async-listener, but I got this PR ready first. No point merging this until we fix async-listener though.

### CODE REVIEW

**Comment by taion** [comment]
Requires https://github.com/othiym23/async-listener/pull/40 for the tests to pass.

**Comment by nmccready** [comment]
Whats the hold up?

**Comment by othiym23** [comment]
Landed as 124205ab642af8b55c29dd6693ce82ce38cbfdaa. Thanks!

> Whats the hold up?

A lil thing called "npm". My day job hasn't left me with as much time to maintain this as I would like. Thanks to all for their patience!

**Comment by taion** [comment]
Thanks!

**Comment by nmccready** [comment]
Thank u

**Pull request closed without merging**
